apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 258267424961.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 258267424961.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 3091eca9
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
